In [3]:
import numpy as np

# We create a 4 x 5 ndarray that contains integers from 0 to 19
X = np.arange(20).reshape(4, 5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [4]:
# We print X
print()
print('X = \n', X)
print()


X = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]



In [6]:
# We select all the elements that are in the 2nd through 4th rows and in the 3rd to 5th columns
Z = X[1:4,2:5]

# We print Z
print('Z = \n', Z)

Z = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [7]:
# We can select the same elements as above using method 2
W = X[1:,2:5]

# We print W
print()
print('W = \n', W)


W = 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [8]:
# We select all the elements that are in the 1st through 3rd rows and in the 3rd to 4th columns
Y = X[:3,2:5]

# We print Y
print()
print('Y = \n', Y)


Y = 
 [[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]


In [9]:
# We select all the elements in the 3rd row
v = X[2,:]

# We print v
print()
print('v = ', v)


v =  [10 11 12 13 14]


In [10]:
# We select all the elements in the 3rd column
q = X[:,2]

# We print q
print()
print('q = ', q)


q =  [ 2  7 12 17]


In [11]:
# We select all the elements in the 3rd column but return a rank 2 ndarray
R = X[:,2:3]

# We print R
print()
print('R = \n', R)


R = 
 [[ 2]
 [ 7]
 [12]
 [17]]
